Fix longstanding issue TypeError: e.map is not a function (#5170)
Fixes #4868
This took so long to track down. I am convinced `@ts-expect-error` is
*always an error*.